name: survey_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  connectivity_plus: ^2.3.5
  flutter:
    sdk: flutter
  flutter_background_service: ^2.1.3
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  hive_generator: ^1.1.3
  json_serializable: ^6.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
